import React, { useState } from 'react';
import { UserRole } from '../../types';
import { Card, Button, Select, Table, THead, TBody, TH, TR, TD, TableEmpty, Badge, useToast } from '../ui';

/**
 * Access code generator. Spec: docs/design/03-components.md section 18.
 *
 * The reveal panel is the addition. The code is the product of this screen, and it
 * previously appeared only as another table row, which is the one place a value that has
 * to be transcribed and sent to someone should not live.
 *
 * The code renders in a monospace face because access codes get read aloud over the
 * phone, and telling 0 from O is a correctness requirement rather than a style choice.
 */

const ROLE_LABELS = {
  [UserRole.ADMIN]: 'Government administrator',
  [UserRole.CONTRACTOR]: 'Contractor',
  [UserRole.DEVELOPER_ADMIN]: 'Developer',
};

export const AccessCodeManager = ({ accessCodes = [], onGenerate }) => {
  const [selectedRole, setSelectedRole] = useState(UserRole.CONTRACTOR);
  const [latest, setLatest] = useState(null);
  const [copied, setCopied] = useState(false);
  const [generating, setGenerating] = useState(false);
  const toast = useToast();

  const handleGenerate = async () => {
    setGenerating(true);
    setCopied(false);
    const result = await onGenerate(selectedRole);
    setGenerating(false);

    // The store may return the code, or push it into the list. Handle both.
    const code = result?.code || result || null;
    if (typeof code === 'string') setLatest({ code, role: selectedRole });
  };

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(latest.code);
      setCopied(true);
      toast.success('Access code copied to the clipboard.');
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      toast.error('Could not copy automatically. Select the code and copy it manually.');
    }
  };

  return (
    <div className="flex flex-col gap-6">
      <Card padding="lg">
        <h2 className="text-h3 text-fg">Generate an access code</h2>
        <p className="mt-1 max-w-prose text-caption text-fg-tertiary">
          A code lets one person create an account with the role you choose. Each code works once.
        </p>

        <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end">
          <Select
            label="Role"
            value={selectedRole}
            onChange={(e) => setSelectedRole(e.target.value)}
            fieldClassName="w-full sm:w-72"
          >
            {Object.entries(ROLE_LABELS).map(([value, label]) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </Select>
          <Button
            variant="primary"
            size="md"
            onClick={handleGenerate}
            loading={generating}
            leadingIcon={<i className="fas fa-key" aria-hidden="true" />}
          >
            Generate code
          </Button>
        </div>

        {/* Reveal panel. Announced politely so the code is not a purely visual result. */}
        {latest && (
          <Card variant="inset" padding="lg" className="mt-6 animate-fade-in">
            <div role="status" aria-live="polite">
              <p className="text-overline uppercase text-fg-tertiary">
                New code for {ROLE_LABELS[latest.role]}
              </p>
              <div className="mt-3 flex flex-wrap items-center gap-4">
                <code className="select-all font-mono text-h2 tracking-[0.08em] text-fg">{latest.code}</code>
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={copy}
                  leadingIcon={<i className={copied ? 'fas fa-check' : 'fas fa-copy'} aria-hidden="true" />}
                >
                  {copied ? 'Copied' : 'Copy'}
                </Button>
              </div>
              <p className="mt-3 text-caption text-fg-tertiary">
                Share this code only with the person you are inviting. It works once.
              </p>
            </div>
          </Card>
        )}
      </Card>

      <div>
        <h2 className="mb-3 text-h3 text-fg">Issued codes</h2>
        <Table caption="Access codes that have been issued">
          <THead>
            <TR>
              <TH>Code</TH>
              <TH>Role</TH>
              <TH>Status</TH>
              <TH className="hidden sm:table-cell">Generated by</TH>
            </TR>
          </THead>
          <TBody>
            {accessCodes.length === 0 ? (
              <TableEmpty colSpan={4}>No codes have been generated yet.</TableEmpty>
            ) : (
              accessCodes.map((ac, idx) => (
                <TR key={ac.code || idx}>
                  <TD className="font-mono tracking-wider text-fg">{ac.code}</TD>
                  <TD>{ROLE_LABELS[ac.role] || ac.role}</TD>
                  <TD>
                    <Badge tone={ac.isUsed ? 'stalled' : 'progress'} size="sm">
                      {ac.isUsed ? 'Used' : 'Active'}
                    </Badge>
                  </TD>
                  <TD className="hidden sm:table-cell">{ac.generatedBy}</TD>
                </TR>
              ))
            )}
          </TBody>
        </Table>
      </div>
    </div>
  );
};
