import React, { useState } from 'react';
import { UserRole } from '../../types';

export const AccessCodeManager = ({ accessCodes, onGenerate }) => {
    const [selectedRole, setSelectedRole] = useState(UserRole.CONTRACTOR);

    return (
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 mb-12">
            <div className="flex justify-between items-center border-b pb-4 mb-6">
                <h2 className="text-xl font-bold text-gray-800">Generate Access Codes</h2>
                <span className="text-xs bg-blue-50 text-blue-700 px-3 py-1 rounded-full font-bold">Secure Invite System</span>
            </div>

            <div className="flex flex-col md:flex-row gap-4 items-end mb-8 bg-gray-50 p-4 rounded-lg">
                <div className="w-full md:w-auto">
                    <label className="block text-xs font-bold uppercase text-gray-500 mb-1">Select User Role</label>
                    <div className="relative">
                        <select
                            className="appearance-none border border-gray-300 p-3 rounded-lg w-full md:w-64 focus:ring-2 focus:ring-secondary focus:outline-none bg-white font-medium"
                            value={selectedRole}
                            onChange={(e) => setSelectedRole(e.target.value)}
                        >
                            <option value={UserRole.ADMIN}>Government Admin</option>
                            <option value={UserRole.CONTRACTOR}>Contractor</option>
                            <option value={UserRole.DEVELOPER_ADMIN}>Developer</option>
                        </select>
                        <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                            <i className="fas fa-chevron-down text-xs"></i>
                        </div>
                    </div>
                </div>
                <button
                    onClick={() => onGenerate(selectedRole)}
                    className="w-full md:w-auto bg-secondary text-white px-6 py-3 rounded-lg font-bold hover:bg-amber-600 transition-colors shadow-sm"
                >
                    <i className="fas fa-key mr-2"></i> Generate Code
                </button>
            </div>

            <div className="overflow-hidden rounded-lg border border-gray-200">
                <table className="w-full text-left text-sm">
                    <thead className="bg-gray-100 text-gray-600 uppercase text-xs font-bold">
                        <tr>
                            <th className="px-4 py-3">Access Code</th>
                            <th className="px-4 py-3">Role</th>
                            <th className="px-4 py-3">Status</th>
                            <th className="px-4 py-3">Generated By</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100 bg-white">
                        {accessCodes.length === 0 ? (
                            <tr><td colSpan={4} className="p-4 text-center text-gray-500">No codes generated yet.</td></tr>
                        ) : (
                            accessCodes.map((ac, idx) => (
                                <tr key={idx} className="hover:bg-gray-50 transition-colors">
                                    <td className="px-4 py-3 font-mono font-bold text-primary tracking-wide">{ac.code}</td>
                                    <td className="px-4 py-3">
                                        <span className="bg-gray-100 px-2 py-1 rounded text-xs">{ac.role}</span>
                                    </td>
                                    <td className="px-4 py-3">
                                        {ac.isUsed ?
                                            <span className="text-red-600 bg-red-50 px-2 py-1 rounded-full text-xs font-bold">Used</span> :
                                            <span className="text-green-600 bg-green-50 px-2 py-1 rounded-full text-xs font-bold">Active</span>
                                        }
                                    </td>
                                    <td className="px-4 py-3 text-gray-500 text-xs italic">{ac.generatedBy}</td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
};
